import Animated from '@/components/homeComponents/Animated/Animated'
import Features from '@/components/homeComponents/Features/Features'
import GraveSuccess from '@/components/homeComponents/GraveSuccess/GraveSuccess'
import Ready from '@/components/homeComponents/Ready/Ready'
import Sponsors from '@/components/homeComponents/Sponsors/Sponsors'
import Success from '@/components/homeComponents/Success/Success'
import Slider from '@/components/homeComponents/Swiper/Slider'
import Image from 'next/image'

export const metadata = {
  title: 'Career Puzzle | Home',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className="min-h-screen">
      <Slider></Slider>
      <Animated></Animated>
      <Features></Features>
      <Success></Success>
      <Ready></Ready>
      <GraveSuccess></GraveSuccess>
      <Sponsors></Sponsors>
    </main>
  )
}
